import type { JSONFormConfig } from "~/utils/form-schema";

export const formTemplates: JSONFormConfig[] = [
  // 1. Contact Form
  {
    id: "contact",
    title: "Contact Us",
    description: "Send us a message and we'll get back to you.",
    submitButtonText: "Send Message",
    pages: [
      {
        id: "contact-page",
        title: "Contact",
        fields: [
          {
            name: "firstName",
            label: "First Name",
            component: "UInput",
            type: "text",
            placeholder: "John",
            colSpan: 6,
            row: 1,
            validation: [{ type: "min", value: 2, message: "At least 2 characters" }],
          },
          {
            name: "lastName",
            label: "Last Name",
            component: "UInput",
            type: "text",
            placeholder: "Doe",
            colSpan: 6,
            row: 1,
            validation: [{ type: "min", value: 2, message: "At least 2 characters" }],
          },
          {
            name: "email",
            label: "Email Address",
            component: "UInput",
            type: "email",
            placeholder: "john@example.com",
            colSpan: 12,
            row: 2,
            validation: [
              { type: "required", message: "Email is required" },
              { type: "email", message: "Enter a valid email" },
            ],
          },
          {
            name: "subject",
            label: "Subject",
            component: "USelect",
            type: "text",
            placeholder: "Select subject",
            colSpan: 12,
            row: 3,
            items: [
              { label: "General Inquiry", value: "general" },
              { label: "Support", value: "support" },
              { label: "Partnership", value: "partnership" },
              { label: "Other", value: "other" },
            ],
            validation: [{ type: "required", message: "Please select a subject" }],
          },
          {
            name: "subjectOther",
            label: "Describe Your Subject",
            component: "UInput",
            type: "text",
            placeholder: "Briefly describe your topic…",
            colSpan: 12,
            row: 4,
            hiddenIf: [{ op: "neq", field: "subject", value: "other" }],
            dependsOn: ["subject"],
            clearOnChange: true,
          },
          {
            name: "message",
            label: "Message",
            component: "UTextarea",
            type: "textarea",
            placeholder: "Your message here…",
            colSpan: 12,
            row: 5,
            props: { rows: 4 },
            validation: [{ type: "min", value: 10, message: "At least 10 characters" }],
          },
        ],
      },
    ],
  },
  // 2. Job Application (multi-page)
  {
    id: "job-application",
    title: "Job Application",
    description: "Apply for a position at our company.",
    submitButtonText: "Submit Application",
    previousButtonText: "Back",
    nextButtonText: "Continue",
    pages: [
      {
        id: "personal",
        title: "Personal Info",
        sections: [
          {
            id: "basic",
            title: "Basic Information",
            icon: "i-heroicons-user",
            fields: [
              {
                name: "fullName",
                label: "Full Name",
                component: "UInput",
                type: "text",
                placeholder: "Your full name",
                colSpan: 12,
                row: 1,
                validation: [{ type: "min", value: 3, message: "At least 3 characters" }],
              },
              {
                name: "email",
                label: "Email",
                component: "UInput",
                type: "email",
                placeholder: "you@example.com",
                colSpan: 6,
                row: 2,
                validation: [
                  { type: "required", message: "Email required" },
                  { type: "email", message: "Invalid email" },
                ],
              },
              {
                name: "phone",
                label: "Phone",
                component: "UInput",
                type: "tel",
                placeholder: "+855 xx xxx xxx",
                colSpan: 6,
                row: 2,
                validation: [{ type: "min", value: 8, message: "Enter a valid phone" }],
              },
              {
                name: "gender",
                label: "Gender",
                component: "URadioGroup",
                type: "radio",
                colSpan: 12,
                row: 3,
                items: [
                  { label: "Male", value: "male" },
                  { label: "Female", value: "female" },
                  { label: "Other", value: "other" },
                ],
                props: { orientation: "horizontal" },
                validation: [{ type: "required", message: "Select gender" }],
              },
            ],
          },
        ],
      },
      {
        id: "professional",
        title: "Professional",
        sections: [
          {
            id: "work",
            title: "Work Experience",
            icon: "i-heroicons-briefcase",
            fields: [
              {
                name: "currentPosition",
                label: "Current Position",
                component: "UInput",
                type: "text",
                placeholder: "Software Engineer",
                colSpan: 6,
                row: 1,
                validation: [{ type: "required", message: "Position required" }],
              },
              {
                name: "yearsExp",
                label: "Years of Experience",
                component: "USelect",
                type: "text",
                placeholder: "Select range",
                colSpan: 6,
                row: 1,
                items: [
                  { label: "0–1 years", value: "0-1" },
                  { label: "2–4 years", value: "2-4" },
                  { label: "5–9 years", value: "5-9" },
                  { label: "10+ years", value: "10+" },
                ],
                validation: [{ type: "required", message: "Select experience range" }],
              },
              {
                name: "skills",
                label: "Key Skills",
                component: "UTextarea",
                type: "textarea",
                placeholder: "e.g. Vue 3, Nuxt, TypeScript…",
                colSpan: 12,
                row: 2,
                props: { rows: 3 },
                validation: [{ type: "min", value: 5, message: "At least 5 characters" }],
              },
            ],
          },
        ],
      },
      {
        id: "cover",
        title: "Cover Letter",
        fields: [
          {
            name: "coverLetter",
            label: "Cover Letter",
            component: "UTextarea",
            type: "textarea",
            placeholder: "Tell us why you'd be a great fit…",
            colSpan: 12,
            row: 1,
            props: { rows: 8 },
            validation: [{ type: "min", value: 50, message: "At least 50 characters" }],
          },
          {
            name: "startDate",
            label: "Available Start Date",
            component: "UInput",
            type: "date",
            colSpan: 6,
            row: 2,
          },
          {
            name: "salaryExpectation",
            label: "Salary Expectation (USD/mo)",
            component: "UInput",
            type: "number",
            placeholder: "e.g. 1200",
            colSpan: 6,
            row: 2,
          },
        ],
      },
    ],
  },
  // 3. Event Registration
  {
    id: "event-registration",
    title: "Event Registration",
    description: "Register for our upcoming event.",
    submitButtonText: "Register Now",
    pages: [
      {
        id: "registration-page",
        title: "Registration",
        fields: [
          {
            name: "name",
            label: "Full Name",
            component: "UInput",
            type: "text",
            placeholder: "Your name",
            colSpan: 12,
            row: 1,
            validation: [{ type: "min", value: 2, message: "Name required" }],
          },
          {
            name: "email",
            label: "Email",
            component: "UInput",
            type: "email",
            placeholder: "you@example.com",
            colSpan: 12,
            row: 2,
            validation: [
              { type: "required", message: "Email required" },
              { type: "email", message: "Invalid email" },
            ],
          },
          {
            name: "ticketType",
            label: "Ticket Type",
            component: "URadioGroup",
            type: "radio",
            colSpan: 12,
            row: 3,
            items: [
              { label: "General Admission (Free)", value: "free" },
              { label: "VIP ($50)", value: "vip" },
              { label: "Online Stream (Free)", value: "online" },
            ],
            props: { orientation: "vertical" },
            validation: [{ type: "required", message: "Select a ticket type" }],
          },
          {
            name: "dietary",
            label: "Dietary Requirements",
            component: "USelect",
            type: "text",
            placeholder: "Select if applicable",
            colSpan: 12,
            row: 4,
            hiddenIf: [{ op: "eq", field: "ticketType", value: "online" }],
            dependsOn: ["ticketType"],
            items: [
              { label: "None", value: "none" },
              { label: "Vegetarian", value: "vegetarian" },
              { label: "Vegan", value: "vegan" },
              { label: "Halal", value: "halal" },
              { label: "Gluten-free", value: "gluten-free" },
            ],
          },
          {
            name: "notes",
            label: "Additional Notes",
            component: "UTextarea",
            type: "textarea",
            placeholder: "Anything else we should know?",
            colSpan: 12,
            row: 5,
            props: { rows: 3 },
          },
        ],
      },
    ],
  },
];
